# Generated by Django 4.2.10 on 2024-03-01 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
