# Generated by Django 4.2.10 on 2024-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_evchanginglocation_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseAPiQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=200)),
                ('aqi', models.IntegerField(max_length=100)),
                ('category', models.TextField(max_length=200)),
                ('red', models.IntegerField(max_length=100)),
                ('blue', models.IntegerField(max_length=100)),
                ('green', models.IntegerField(max_length=100)),
                ('coName', models.TextField(max_length=200)),
                ('coValue', models.TextField(max_length=200)),
                ('coSource', models.FloatField(max_length=200)),
                ('coEffect', models.TextField(max_length=200)),
                ('noName', models.TextField(max_length=200)),
                ('noValue', models.FloatField(max_length=200)),
                ('noSource', models.TextField(max_length=200)),
                ('noEffect', models.TextField(max_length=200)),
                ('pm10Name', models.TextField(max_length=200)),
                ('pm10Value', models.FloatField(max_length=200)),
                ('pm10Source', models.TextField(max_length=200)),
                ('pm10Effect', models.TextField(max_length=200)),
                ('generalPopulation', models.TextField(max_length=200)),
                ('heartDiseasePopulation', models.TextField(max_length=200)),
                ('children', models.TextField(max_length=200)),
            ],
        ),
    ]
