# Generated by Django 4.2.10 on 2024-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_responseapiquality_aqi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseapiquality',
            name='aqi',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='blue',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='category',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='children',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='coEffect',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='coName',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='coSource',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='coValue',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='date',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='generalPopulation',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='green',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='heartDiseasePopulation',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='noEffect',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='noName',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='noSource',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='noValue',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='pm10Effect',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='pm10Name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='pm10Source',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='pm10Value',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseapiquality',
            name='red',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
