# Generated by Django 4.2.10 on 2024-03-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_responseapiquality_aqi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseapiquality',
            name='pm25Effect',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='pm25Name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='pm25Source',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='pm25Value',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='so2Effect',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='so2Name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='so2Source',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responseapiquality',
            name='so2Value',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
